### ISSUE TITLE
malloc() issue with more  than 3 values

### ISSUE THREAD

**Issue by vbatoufflet** [collectd/go-collectd#26]
Hi @octo,

I ran into a strange error when trying to implement a plugin using `collect.org/api/plugin`.

When I send more than 3 values in `[]api.Value{}`, I get `malloc()` errors in Collectd.

For example:

```
package main

import (
    "time"

    "collectd.org/api"
    "collectd.org/plugin"
)

type Realloc3 struct{}

func (Realloc3) Read() error {
    if err := plugin.Write(&api.ValueList{
        Identifier: api.Identifier{
            Host:         "example",
            Plugin:       "realloc3",
            Type:         "realloc3",
            TypeInstance: "demo",
        },
        Time:     time.Now(),
        Interval: 10 * time.Second,
        DSNames:  []string{"a", "b", "c"},
        Values:   []api.Value{api.Derive(1), api.Derive(2), api.Derive(3)},
    }); err != nil {
        plugin.Error(err)
    }

    return nil
}

func init() {
    plugin.RegisterRead("realloc3", &Realloc3{})
}

func main() {}
```

gives me:

```
# CGO_CPPFLAGS='-I/usr/include/collectd/core/daemon -I/usr/include/collectd/core' go build -buildmode=c-shared -o realloc3.so realloc3.go

# collectd -f
Initialization complete, entering read-loop.
tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
^CExiting normally.
collectd: Stopping 5 read threads.
collectd: Stopping 5 write threads.
```

but with (which basically adds a fourth value):

```
package main

import (
    "time"

    "collectd.org/api"
    "collectd.org/plugin"
)

type Realloc4 struct{}

func (Realloc4) Read() error {
    if err := plugin.Write(&api.ValueList{
        Identifier: api.Identifier{
            Host:         "example",
            Plugin:       "realloc4",
            Type:         "realloc4",
            TypeInstance: "demo",
        },
        Time:     time.Now(),
        Interval: 10 * time.Second,
        DSNames:  []string{"a", "b", "c", "d"},
        Values:   []api.Value{api.Derive(1), api.Derive(2), api.Derive(3), api.Derive(4)},
    }); err != nil {
        plugin.Error(err)
    }

    return nil
}

func init() {
    plugin.RegisterRead("realloc4", &Realloc4{})
}

func main() {}
```

I get:

```
# CGO_CPPFLAGS='-I/usr/include/collectd/core/daemon -I/usr/include/collectd/core' go build -buildmode=c-shared -o realloc4.so realloc4.go

# collectd -f
Initialization complete, entering read-loop.
collectd: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted

# collectd -f
Initialization complete, entering read-loop.
*** Error in `collectd': malloc(): memory corruption: 0x00007fca08000900 ***
tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
Aborted
```

Did I miss something important or did I do something wrong?

Kind regards,
Vincent

**Comment by vbatoufflet** [comment]
I forgot to mention that Collectd version is 5.5.2.

**Comment by octo** [comment]
Hi @vbatoufflet, thank you for reporting this issue! With your information I managed to reproduce the problem:

```
#0  0x00007ffff7623c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 22624
        selftid = 22638
#1  0x00007ffff7627028 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fffed7f9b60, sa_sigaction = 0x7fffed7f9b60}, sa_mask = {__val = {0, 0, 6595232, 140737353965568, 140737335198554, 140737343643080, 140737335195280, 21474836480, 4294967784, 0, 140737177951272, 140737177951232, 6595232, 1, 
              6597776, 6596912}}, sa_flags = -469762016, sa_restorer = 0x7ffff79ac1c0 <_IO_2_1_stderr_>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff766a6ed in __malloc_assert (
    assertion=assertion@entry=0x7ffff776ebe8 "(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offs"..., 
    file=file@entry=0x7ffff776a768 "malloc.c", line=line@entry=2372, function=function@entry=0x7ffff776aae6 <__func__.11321> "sysmalloc") at malloc.c:293
No locals.
#3  0x00007ffff766db58 in sysmalloc (av=0x7fffe4000020, nb=48) at malloc.c:2369
        old_top = 0x7fffe40008f0
        snd_brk = 0x0
        front_misalign = <optimized out>
        remainder = <optimized out>
        tried_mmap = <optimized out>
        old_size = 0
        size = <optimized out>
        old_end = 0x7fffe40008f0 "\003"
        brk = 0x0
        correction = <optimized out>
        end_misalign = <optimized out>
        aligned_brk = <optimized out>
        p = <optimized out>
        remainder_size = <optimized out>
        pagemask = 4095
#4  _int_malloc (av=av@entry=0x7fffe4000020, bytes=bytes@entry=32) at malloc.c:3800
        iters = <optimized out>
        nb = 48
        idx = <optimized out>
        bin = <optimized out>
        victim = <optimized out>
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        errstr = 0x0
        __func__ = "_int_malloc"
#5  0x00007ffff76701dc in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3219
        av = 0x7fffe4000020
        oldtop = 0x7fffe40008f0
        p = <optimized out>
        bytes = 32
        sz = 32
        csz = <optimized out>
        oldtopsize = 132880
        mem = <optimized out>
        clearsize = <optimized out>
        nclears = <optimized out>
        d = <optimized out>
        hook = <optimized out>
        __func__ = "__libc_calloc"
#6  0x00007ffff73ea690 in _dlerror_run (operate=operate@entry=0x7ffff73e9fd0 <dlopen_doit>, args=args@entry=0x7fffed7f9c70) at dlerror.c:141
        result = <optimized out>
#7  0x00007ffff73ea0c1 in __dlopen (file=file@entry=0x0, mode=mode@entry=1) at dlopen.c:87
        args = {file = 0x0, mode = 1, new = 0x36, caller = 0x7ffff6f0585c <dispatch_values_wrapper+44>}
#8  0x00007ffff6f0585c in dispatch_values_wrapper (vl=0xc4200be000) at /home/octo/go/src/collectd.org/plugin/c.go:30
        hnd = <optimized out>
#9  0x00007ffff6f05adb in _cgo_75a6c6751aff_C2func_dispatch_values_wrapper (v=0xc420040c08) at /home/octo/go/src/collectd.org/plugin/plugin.go:142
        _cgo_errno = <optimized out>
        a = 0xc420040c08
        stktop = 0xc420040fd0 ""
        r = <optimized out>
#10 0x00007ffff6eacbe8 in runtime.asmcgocall () at /opt/go/src/runtime/asm_amd64.s:590
No locals.
#11 0x000000c420040b80 in ?? ()
No symbol table info available.
#12 0x00007ffff6e5c9f3 in runtime.cgocall (fn=0x0, arg=0x7fffed7f9d78, ~r2=-152384386) at /opt/go/src/runtime/cgocall.go:115
        errno = 0
        mp = 0xc420000680
        _g_ = 0x7ffff6eaaf22 <runtime.systemstack+114>
#13 0x00007fffed7f9d38 in ?? ()
No symbol table info available.
#14 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by vbatoufflet** [comment]
Hi @octo,

Do you know if there is any workaround?

**Comment by vbatoufflet** [comment]
Hi @octo,

Did you had a chance to take look at this issue yet?

**Comment by octo** [comment]
I looked, I could reproduce, but I have no idea what's going on. Any help is welcome :)

**Comment by falzm** [comment]
Well, at least that's honest 😅

**Comment by iMilnb** [comment]
FWIW I've been hit by the same bug, 3 DSNames and Values, all clear. 4 DSNames and Values, segfault.
